<div class="footer">
    <div class="container">
        <div class="hidden-xs col-sm-5"><strong>Truyện Full</strong> - <a href="http://truyenfull.vn" title="Đọc truyện online">Đọc truyện</a> online, <a href="http://truyenfull.vn" title="Đọc truyện chữ">đọc truyện</a> chữ, <a href="http://truyenfull.vn" title="Truyện hay">truyện hay</a>. Website luôn cập nhật những bộ <a href="http://truyenfull.vn/danh-sach/truyen-moi/" title="Truyện mới">truyện mới</a> thuộc các thể loại đặc sắc như <a href="http://truyenfull.vn/the-loai/tien-hiep/" title="Truyện tiên hiệp">truyện tiên hiệp</a>, <a href="http://truyenfull.vn/the-loai/kiem-hiep/" title="Truyện kiếm hiệp">truyện kiếm hiệp</a>, hay <a href="http://truyenfull.vn/the-loai/ngon-tinh/" title="Truyện ngôn tình">truyện ngôn tình</a> một cách nhanh nhất. Hỗ trợ mọi thiết bị như di động và máy tính bảng.</div>
        <ul class="col-xs-12 col-sm-7 list-unstyled">
            <li class="text-right pull-right"><a href="http://truyenfull.vn/contact/" title="Contact">Contact</a> - <a href="http://truyenfull.vn/tos/" title="Terms of Service">ToS</a> - <a href="http://truyenfull.vn/sitemap.xml" title="Sitemap" target="_blank">Sitemap</a><a class="backtop" href="#wrap" rel="nofollow"><span class="glyphicon glyphicon-upload"></span></a>
                <!--<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=BMYGJSKTRBZXU" title="Donate - Ủng hộ" target="_blank" rel="nofollow">Donate</a>--></li>
            <li class="hidden-xs tag-list"><a href="http://truyenfull.vn/ma-thien-ky/" title="ma thien ky">ma thien ky</a> <a href="http://truyenfull.vn/tien-nghich/" title="tien nghich">tien nghich</a> <a href="http://truyenfull.vn/thieu-gia-ac-ma-dung-hon-toi/" title="thieu gia ac ma dung hon toi">thieu gia ac ma dung hon toi</a> <a href="http://truyenfull.vn/the-loai/dam-my/" title="truyen dam my">truyen dam my</a> <a href="http://truyenfull.vn/chua-te-chi-vuong/" title="chua te chi vuong">chua te chi vuong</a> <a href="http://truyenfull.vn/tam-sinh-tam-the-thap-ly-dao-hoa/" title="tam sinh tam the thap ly dao hoa">tam sinh tam the thap ly dao hoa</a> <a href="http://truyenfull.vn/linh-vu-thien-ha/" title="linh vu thien ha">linh vu thien ha</a> <a href="http://truyenfull.vn/quan-khi/" title="quan khi">quan khi</a> <a href="http://truyenfull.vn/dai-thieu-gia-em-lay-cau/" title="dai thieu gia em lay cau">dai thieu gia em lay cau</a> <a href="http://truyenfull.vn/doc-ton-tam-gioi/" title="doc ton tam gioi">doc ton tam gioi</a> <a href="http://truyenfull.vn/quan-thuat/" title="quan thuat">quan thuat</a> <a href="http://truyenfull.vn/quan-sach/" title="quan sach">quan sach</a> <a href="http://truyenfull.vn/quan-bang/" title="quan bang">quan bang</a> <a href="http://truyenfull.vn/tru-tien/" title="tru tien">tru tien</a> <a href="http://truyenfull.vn/lac-hong-ky/" title="lac hong ky">lac hong ky</a></li>
        </ul>
    </div>
</div>